### ISSUE TITLE
`Map String a` <-> Object

### ISSUE THREAD

**Issue by flip111** [purescript-contrib/purescript-argonaut-codecs#105]
Following the discussion here https://github.com/purescript-contrib/purescript-argonaut-codecs/issues/101

Could an `EncodeJson` / `DecodeJson` for `Map String a` be provided that convert from/to a javascript object instead of an array?

I think that this is the desired behavior in nearly all situations and when it isn't people can manually write their codec.

**Comment by garyb** [comment]
The proposed instance overlaps with the existing `Map` instance, so it's not really an option unfortunately. 

If you want that encoding for with the least amount of work possible, maybe use an [`Object`](https://pursuit.purescript.org/packages/purescript-foreign-object/docs/Foreign.Object) rather than a `Map` - it has much the same interface as `Map` but is restricted to `String` keys and will encode the way you're looking for.
