### ISSUE TITLE
why is `L.insertAt 0 h t` is used?

### ISSUE THREAD

**Issue by srghma** [purescript-contrib/purescript-argonaut-codecs#78]
here 

https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/fdd873cbf13865f42bf431bf4ef97f40adb378ed/src/Data/Argonaut/Encode/Class.purs#L82

why  `L.insertAt 0 h t`??

it is equal to `Just (h : t)`

why not `(h : t)` ?

**Comment by thomashoneyman** [comment]
I'm not sure why it was written that way instead of `encodeJson (h : t)`. For context, this is the implementation of `insertAt`:

https://github.com/purescript/purescript-lists/blob/62900a56f6864638c952575dfd211a1cc55be7da/src/Data/List.purs#L314-L317

...where `insertAt 0 x xs = Just (x : xs)`, so it seems like we might as well have written `(h : t)` instead to avoid the unnecessary `Just` wrapper.

We can use your suggestion instead if you'd like to open a PR.

**Comment by srghma** [comment]
I have refactored it here https://github.com/purescript-contrib/purescript-argonaut-codecs/pull/74

**Comment by thomashoneyman** [comment]
Got it. I've linked this issue to the pull request so that this will be closed when it merges.
