### ISSUE TITLE
Encode/Decode Natural

### ISSUE THREAD

**Issue by f-f** [purescript-contrib/purescript-argonaut-codecs#95]
Would a PR to implement `EncodeJson`/`DecodeJson` for [`Natural`](https://pursuit.purescript.org/packages/purescript-naturals/3.0.0/docs/Data.Natural#t:Natural) be welcome?

**Comment by thomashoneyman** [comment]
Unfortunately, since `Natural` is outside of core / contrib we won't bring in the dependency here. If you're using automatic record decoding that's unfortunate, but if you're manually writing encoders / decoders you could decode as an int and then immediately parse as a natural -- something (hand-wavy) like thisS

```purs
myField <- note (TypeMismatch "Natural") Natural.parse =<< rec .: "natural_field"
```
